### ISSUE TITLE
Fix bug with booru.konachen

### ISSUE THREAD

**Issue by nitros12** [nitros12/LoliBot-Hy#1]
Konachan is currently fucked, provides this error:
```Command raised an exception: ClientConnectorError: [Errno 101] Cannot connect to host konachan.com:None ssl:False [Can not connect to konachan.com:None [Network is unreachable]]
Traceback (most recent call last):

  File "/usr/lib/python3.6/site-packages/aiohttp/connector.py", line 710, in _create_direct_connection
    local_addr=self._local_addr)

  File "uvloop/loop.pyx", line 1568, in create_connection (uvloop/loop.c:30607)

  File "uvloop/loop.pyx", line 1546, in uvloop.loop.Loop.create_connection (uvloop/loop.c:30234)

  File "uvloop/handles/tcp.pyx", line 168, in uvloop.loop.TCPTransport.connect (uvloop/loop.c:81020)

  File "uvloop/handles/tcp.pyx", line 192, in uvloop.loop._TCPConnectRequest.connect (uvloop/loop.c:81280)

OSError: [Errno 101] Network is unreachable


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/usr/lib/python3.6/site-packages/aiohttp/connector.py", line 378, in connect
    proto = yield from self._create_connection(req)

  File "/usr/lib/python3.6/site-packages/aiohttp/connector.py", line 687, in _createconnection
    , proto = yield from self._create_direct_connection(req)

  File "/usr/lib/python3.6/site-packages/aiohttp/connector.py", line 737, in _create_direct_connection
    (req.host, req.port, exc.strerror)) from exc

aiohttp.clientexceptions.ClientConnectorError: [Errno 101] Can not connect to konachan.com:None [Network is unreachable]


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)

  File "/home/nitros/bot/bot/cogs/booru.py", line 240, in konachan
    await ctx.send(embed=await self.konachan.parse_req_tags(*tags))

  File "/home/nitros/bot/bot/cogs/booru.py", line 147, in parse_req_tags
    valid = await self.find_valid_url(responses, key="file_url")

  File "/home/nitros/bot/bot/cogs/booru.py", line 38, in find_valid_url
    async with self.session.head(base + url, headers=self.headers) as resp:

  File "/usr/lib/python3.6/site-packages/aiohttp/client.py", line 603, in aenter
    self._resp = yield from self._coro

  File "/usr/lib/python3.6/site-packages/aiohttp/client.py", line 231, in _request
    conn = yield from self._connector.connect(req)

  File "/usr/lib/python3.6/site-packages/aiohttp/connector.py", line 383, in connect
    .format(key, exc.strerror)) from exc

aiohttp.client_exceptions.ClientConnectorError: [Errno 101] Cannot connect to host konachan.com:None ssl:False [Can not connect to konachan.com:None [Network is unreachable]]


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/usr/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 873, in invoke
    yield from ctx.command.invoke(ctx)

  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 468, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)

  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 71, in wrapped
    raise CommandInvokeError(e) from e

discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ClientConnectorError: [Errno 101] Cannot connect to host konachan.com:None ssl:False [Can not connect to konachan.com:None [Network is unreachable]]

**Comment by nitros12** [comment]
Solved by removing booru from bot ;^)
